# Generated by Django 4.2.4 on 2025-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="USER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=500)),
                ("recipename", models.CharField(max_length=500)),
                ("dietlabel", models.CharField(max_length=500)),
                ("cuisine", models.CharField(max_length=500)),
                ("dish", models.CharField(max_length=500)),
                ("ingredients", models.CharField(max_length=500)),
                ("health", models.CharField(max_length=500)),
                ("image", models.FileField(upload_to="RECIPE_APP/images/")),
            ],
        ),
    ]
