# Generated by Django 4.2.4 on 2025-10-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RECIPE_APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="user",
            order_with_respect_to="username",
        ),
    ]
