# Generated by Django 4.2.4 on 2025-10-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RECIPE_APP", "0002_alter_user_order_with_respect_to"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="user",
            order_with_respect_to=None,
        ),
    ]
